# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\vspread_model_v1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpreadEEGui(object):
    def setupUi(self, SpreadEEGui):
        SpreadEEGui.setObjectName("SpreadEEGui")
        SpreadEEGui.resize(820, 621)
        SpreadEEGui.setMinimumSize(QtCore.QSize(820, 620))
        self.centralwidget = QtWidgets.QWidget(SpreadEEGui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbModelInitialization = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbModelInitialization.setFont(font)
        self.gbModelInitialization.setObjectName("gbModelInitialization")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gbModelInitialization)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtCovid19TestSrc = QtWidgets.QLineEdit(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtCovid19TestSrc.setFont(font)
        self.txtCovid19TestSrc.setObjectName("txtCovid19TestSrc")
        self.horizontalLayout.addWidget(self.txtCovid19TestSrc)
        self.btnFetchDataAndProcess = QtWidgets.QPushButton(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnFetchDataAndProcess.setFont(font)
        self.btnFetchDataAndProcess.setObjectName("btnFetchDataAndProcess")
        self.horizontalLayout.addWidget(self.btnFetchDataAndProcess)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtNDaysAgo = QtWidgets.QLineEdit(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNDaysAgo.setFont(font)
        self.txtNDaysAgo.setObjectName("txtNDaysAgo")
        self.gridLayout.addWidget(self.txtNDaysAgo, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtFractionGenerationInt = QtWidgets.QLineEdit(self.gbModelInitialization)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFractionGenerationInt.setFont(font)
        self.txtFractionGenerationInt.setObjectName("txtFractionGenerationInt")
        self.gridLayout.addWidget(self.txtFractionGenerationInt, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.figThinFigure = QtWidgets.QVBoxLayout()
        self.figThinFigure.setObjectName("figThinFigure")
        self.horizontalLayout_3.addLayout(self.figThinFigure)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.gbModelInitialization)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.gbModelInitialization)
        self.gbApplicationLog = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbApplicationLog.setFont(font)
        self.gbApplicationLog.setObjectName("gbApplicationLog")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbApplicationLog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtConsole = QtWidgets.QTextEdit(self.gbApplicationLog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtConsole.setFont(font)
        self.txtConsole.setObjectName("txtConsole")
        self.verticalLayout_3.addWidget(self.txtConsole)
        self.verticalLayout_2.addWidget(self.gbApplicationLog)
        SpreadEEGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpreadEEGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        SpreadEEGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpreadEEGui)
        self.statusbar.setObjectName("statusbar")
        SpreadEEGui.setStatusBar(self.statusbar)
        self.actionLog = QtWidgets.QAction(SpreadEEGui)
        self.actionLog.setCheckable(True)
        self.actionLog.setObjectName("actionLog")
        self.actionRefresh_data_file = QtWidgets.QAction(SpreadEEGui)
        self.actionRefresh_data_file.setObjectName("actionRefresh_data_file")
        self.actionRefresh_predictor = QtWidgets.QAction(SpreadEEGui)
        self.actionRefresh_predictor.setObjectName("actionRefresh_predictor")
        self.menuEdit.addAction(self.actionRefresh_data_file)
        self.menuEdit.addAction(self.actionRefresh_predictor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(SpreadEEGui)
        QtCore.QMetaObject.connectSlotsByName(SpreadEEGui)

    def retranslateUi(self, SpreadEEGui):
        _translate = QtCore.QCoreApplication.translate
        SpreadEEGui.setWindowTitle(_translate("SpreadEEGui", "AE Predictor"))
        self.gbModelInitialization.setTitle(_translate("SpreadEEGui", "Model initialization"))
        self.label.setText(_translate("SpreadEEGui", "Data source file URL:"))
        self.txtCovid19TestSrc.setText(_translate("SpreadEEGui", " https://opendata.digilugu.ee/opendata_covid19_test_results.csv"))
        self.btnFetchDataAndProcess.setText(_translate("SpreadEEGui", "Fetch data and initialize model"))
        self.label_2.setText(_translate("SpreadEEGui", "Stop initialization N days ago from current date:"))
        self.txtNDaysAgo.setText(_translate("SpreadEEGui", "10"))
        self.label_3.setText(_translate("SpreadEEGui", "Fraction of generation interval for new infections"))
        self.txtFractionGenerationInt.setText(_translate("SpreadEEGui", "0.8"))
        self.gbApplicationLog.setTitle(_translate("SpreadEEGui", "Application log"))
        self.menuFile.setTitle(_translate("SpreadEEGui", "File"))
        self.menuView.setTitle(_translate("SpreadEEGui", "View"))
        self.menuEdit.setTitle(_translate("SpreadEEGui", "Edit"))
        self.actionLog.setText(_translate("SpreadEEGui", "Log"))
        self.actionRefresh_data_file.setText(_translate("SpreadEEGui", "Refresh data file"))
        self.actionRefresh_predictor.setText(_translate("SpreadEEGui", "Refresh predictor"))

